# BASIC COMMAND OF NUMPY 

In [21]:
import numpy as np
import sys

In [137]:
# basic command to create array with numpy
a = np.array([1,2,3])
A = np.reshape(a, (3,1))
print(A)
print(a)

# define kind of variable
b = np.array([1,2,3],dtype='int32')

# create 2D array
c = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],[11,12,13,14,15,16,17,18,19,11,12,13,14,15,16,17,18]])
# print matrix
print(a)

# print type
print(a.dtype)

# print dimension of array
print(a.ndim)
print(c.ndim)

# access data in array with index
print(a[0])

# access data of array 2D c[row,column]#
print(c[0,2])

# print size of array
print(a.itemsize , "bytes")

(3,)
[[1]
 [2]
 [3]]
[1 2 3]
[1 2 3]
int64
1
2
1
3
8 bytes


### How are Lists different from Numpy ?

Numpy is faster than list

In [26]:
a1 = np.array([4,5,6])
print(a * a1)

[ 4 10 18]


In [29]:
# get a specific row
c[0,:]

array([1, 2, 3])

In [31]:
# get a specific column
c[:,1]

array([2, 5])

In [61]:
# get a little more fancy [startindex:endindex:stepsize]#
# if we use endindex -1 it will access on starting index to index that stay before last index
print(c[0,1:17:3])
print(c[0,1:-1:3])

[ 2  5  8 11 14 17]
[ 2  5  8 11 14]


In [65]:
# changing value in array
c[1,5] = 0
print(c)

# if we want to change value of index more than 1 in 1 command
c[:,2] = 0
print(c)

c[:,1] = [100,200]
print(c)

[[ 1  2  0  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [11 12  0 14 15  0 17 18 19 11 12 13 14 15 16 17 18]]
[[ 1  2  0  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [11 12  0 14 15  0 17 18 19 11 12 13 14 15 16 17 18]]
[[  1 100   0   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
 [ 11 200   0  14  15   0  17  18  19  11  12  13  14  15  16  17  18]]


In [69]:
# array 3D
d = np.array([ [[1,2,3],[4,5,6]] , [[11,12,13],[14,15,16]] ])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [72]:
# get a specific element
print(d[1,1,2])

# replace
d[:,1,:] = [[9,9,9],[8,8,8]]
print(d)

8
[[[ 1  2  3]
  [ 9  9  9]]

 [[11 12 13]
  [ 8  8  8]]]


In [76]:
# All 0s matrix
# (something,something) is tuple and tuple is not have ability to assignment item
# [something,something] is list
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
d = np.zeros((4,2,3),dtype='int32')
print(d)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [82]:
# fill any number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [84]:
# change all value in matrix (array,number)#
np.full_like(d,4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]], dtype=int32)

In [86]:
# random decimal number (row,column)
np.random.rand(4,2)

array([[0.47587825, 0.40524882],
       [0.39515554, 0.45255649],
       [0.74176706, 0.51629972],
       [0.76746071, 0.82849059]])

In [87]:
# random decimal number (number of matrix,row,column)
np.random.rand(3,4,2)

array([[[4.93011136e-01, 2.40075797e-01],
        [4.82263733e-01, 5.88632374e-01],
        [6.88805587e-01, 1.83794101e-01],
        [4.33621944e-01, 7.17071645e-04]],

       [[1.06281286e-01, 5.47921639e-01],
        [1.70525412e-01, 1.73027564e-01],
        [9.20917264e-01, 8.20166120e-01],
        [6.20774364e-01, 8.06606628e-01]],

       [[7.92236516e-01, 1.94224616e-01],
        [4.06803253e-01, 4.72863835e-01],
        [2.65821226e-01, 3.36717457e-01],
        [4.01817630e-01, 4.28616204e-01]]])

In [89]:
# random with dimension of d
np.random.random_sample(d.shape)

array([[[0.24110618, 0.8506047 , 0.49169451],
        [0.94792479, 0.51518098, 0.93821264]],

       [[0.60576107, 0.45601358, 0.66344603],
        [0.5620743 , 0.07218268, 0.22909232]],

       [[0.56781966, 0.86073464, 0.86587618],
        [0.94971361, 0.28274644, 0.85403123]],

       [[0.13769481, 0.25009365, 0.60419531],
        [0.67458934, 0.11003918, 0.57387394]]])

In [92]:
# random integer value (maximum value,size)
np.random.randint(7,size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 1]])

In [93]:
# create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
arr = np.array([1,2,3])
# (array,number of repetitions,axis)
r1 = np.repeat(arr,4,axis=0)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [100]:
arr = np.array([[1,2,3]])
# (array,number of repetitions,axis)
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [115]:
output = np.ones((5,5))
r1 = np.zeros((3,3))
print(output)
print(r1)

output[1:4,1:4] = r1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [118]:
# matrix multiplication
a1 = np.ones((2,3))
print(a1)
a2 = np.full((3,2),2)
print(a2)
ans = np.matmul(a1,a2)
print(ans)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [120]:
# find det
a1 = np.identity(3)
np.linalg.det(a1)

1.0

#### Statistics

In [123]:
# find min
stat = np.array([[1,2,3],[4,5,6]])
np.min(stat)

1

In [124]:
# find max
stat = np.array([[1,2,3],[4,5,6]])
np.max(stat)

6

In [127]:
# find max in the other axis
stat = np.array([[1,2,3],[4,5,6]])
np.max(stat,axis=1)

array([3, 6])

In [128]:
# sum 
np.sum(stat,axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [130]:
# vertical stacking
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

r1 = np.vstack((array1,array2))
print(r1)

[[1 2 3]
 [4 5 6]]


In [131]:
# horizontal stacking
r2 = np.hstack((array1,array2))
print(r2)

[1 2 3 4 5 6]


### Application of numpy

Mathematics: mathlab
Ploting: matplotlib
Back-end: pandas

## Pandas

In [140]:
import pandas as pd

In [144]:
# creating series
item = ["Apple","Banana","Mango"]
pd.Series(item)

0     Apple
1    Banana
2     Mango
dtype: object

In [145]:
inx = [1,2,3]
pd.Series(item,index=inx)

1     Apple
2    Banana
3     Mango
dtype: object

In [146]:
# creating DataFrame
datas = [10,20,30,40,50] # list
df = pd.DataFrame(datas)

0
0  10
1  20
2  30
3  40
4  50

In [150]:
# creating dataframe with custom key
datas = [['Kasinphat','Ketchom'],['Phatsakorn','Something'],['Panumeth','Something']]
cols = ['fName','lName']

df = pd.DataFrame(datas,columns=cols)
df

fName      lName
0   Kasinphat    Ketchom
1  Phatsakorn  Something
2    Panumeth  Something

In [ ]:
# creating dataframe from list with zip
